version: "3.9"
services:
  db:
    image: postgres:16
    container_name: receipts_db
    environment:
      POSTGRES_USER: receipts
      POSTGRES_PASSWORD: receipts
      POSTGRES_DB: receipts
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U receipts -d receipts"]
      interval: 5s
      timeout: 5s
      retries: 10
volumes:
  pg_data:
